apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"odoo","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"odoo"}},"template":{"metadata":{"labels":{"app":"odoo"}},"spec":{"containers":[{"env":[{"name":"HOST","value":"postgres"},{"name":"USER","value":"odoo"},{"name":"PASSWORD","value":"odoo"},{"name":"DATABASE","value":"postgres"}],"image":"tazamun/test-hotel:test1.3","imagePullPolicy":"Always","name":"odoo","ports":[{"containerPort":8069}]}],"restartPolicy":"Always"}}}}
    kubernetes.io/change-cause: kubectl set image deployment odoo odoo=tazamun/test-hotel:test1.5
      --record=true
  creationTimestamp: "2024-11-04T13:41:49Z"
  generation: 6
  name: odoo
  namespace: default
  resourceVersion: "3188214"
  uid: a7e41ef5-35e1-4746-bfb3-bce3f3e4adb6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: odoo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: HOST
          value: postgres
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
        - name: DATABASE
          value: hotel
        image: tazamun/hotel:latest
        imagePullPolicy: Always
        name: odoo
        ports:
        - containerPort: 8069
          protocol: TCP
        - containerPort: 8071
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-04T13:42:31Z"
    lastUpdateTime: "2024-11-04T13:42:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-11-04T13:41:49Z"
    lastUpdateTime: "2024-11-06T05:52:10Z"
    message: ReplicaSet "odoo-5f6cc4b669" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
