apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  type: NodePort
  ports:
  - port: 8069
    targetPort: 8069
  selector:
    app: odoo

