# Use the official Python slim image as a base image
FROM python:3.10.15-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Riyadh

# Set timezone to Riyadh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install system dependencies, PostgreSQL, and wkhtmltopdf-compatible libraries
RUN apt-get update && apt-get install -y \
    postgresql-client \
    libpq-dev \
    build-essential \
    libldap2-dev \
    libsasl2-dev \
    curl \
    gnupg2 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libfreetype6 \
    libjpeg62-turbo \
    libpng-dev \
    fontconfig \
    xfonts-base \
    xfonts-75dpi \
    wget \
    git \
    xvfb \
    fonts-noto \
    fonts-noto-cjk \
    fonts-noto-extra \
    nodejs \
    npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb10u6_amd64.deb \
    && apt-get update && apt-get install -y ./libssl1.1_1.1.1n-0+deb10u6_amd64.deb \
    && rm libssl1.1_1.1.1n-0+deb10u6_amd64.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install wkhtmltopdf using the buster version, which is more compatible with the base image
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb \
    && apt-get update && apt-get install -y ./wkhtmltox_0.12.6-1.buster_amd64.deb \
    && rm wkhtmltox_0.12.6-1.buster_amd64.deb

# Install rtlcss globally using npm
RUN npm install -g rtlcss

RUN mkdir -p /opt/odoo-tazamun
WORKDIR /opt/odoo-tazamun

# Create and set permissions for Odoo user and configuration
RUN groupadd -g 1000 odoo && \
    useradd -u 1000 -g odoo -s /bin/sh -m odoo && \
    chown -R odoo:odoo /opt/odoo-tazamun/

RUN git config --global http.postBuffer 524288000

# RUN git clone --depth 1 https://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@github.com/hajikhan/tazamun_internal.git .

RUN git config --global --add safe.directory /opt/odoo-tazamun

# Install Python dependencies
RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt /opt/odoo-tazamun/requirements.txt

RUN pip install gevent
RUN pip install -r /opt/odoo-tazamun/requirements.txt

# Create a session directory with correct permissions
RUN mkdir -p /var/lib/odoo/.local && chown -R odoo:odoo /var/lib/odoo

USER odoo

# Copy Odoo source files and custom modules
COPY . /opt/odoo-tazamun/

# Odoo configuration
COPY odoo.conf /opt/odoo-tazamun/odoo.conf

RUN pip install redis
RUN pip install bcrypt

# Expose Odoo port
EXPOSE 8079 8072

# Expose PostgreSQL port
EXPOSE 5432

# Run Odoo
# CMD ["python", "/opt/odoo-tazamun/odoo-bin", "-c", "/opt/odoo-tazamun/odoo.conf", "-i", "base"]
