apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgresql-data # Sets PV's name
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: local
  capacity:
    storage: 30Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/data" # Sets the volume's path

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: local
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

