apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      containers:
      - name: listener
        image: tazamun/admin:latest  
        imagePullPolicy: Always
        ports:  
        - containerPort: 3000
        env:
        - name: ADMIN_FOLDER
          value: "/"
        - name: domain
          value: ".industry.com.sa"
        - name: Front_BASE
          value: frontend
        - name: MAP_KEY
          value: "AIzaSyAV1g7kB_iY7H3BNjgtbc7Aaa8q1_isDJA"
        - name: PUSHER_APP_KEY
          value: "75951d0e59e5b0b7a9f1"  
        - name: PUSHER_APP_CLUSTER
          value: "eu"  

