apiVersion: v1
kind: Secret
metadata: 
    name: application-secret
type: Opaque
data:
   DB_PASSWORD: Um9sbEAxMzAwMDEw
   APP_KEY: YmFzZTY0OlVsWTVqVG1rbXUzM2EwSkZwNnJmWERJa29BM09hL0xNeVVuQUtJSk85R009