apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
           claimName: laravel-pvc-storage
      initContainers:
        - name: database-migrations
          image: tazamun/backend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          command: ["/bin/sh","-c"]      
          args:
            - php artisan optimize:Clear && cp -Rnp /var/www/html/storage/* /mnt
          volumeMounts:
           - name: laravel-storage
             mountPath: /mnt 
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: tazamun/backend:nginx
          resources: {}
            # limits:
            #   cpu: 500m
            #   memory: 50M
          ports:
            - containerPort: 80
        - name: fpm
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          resources: {}
          image: tazamun/backend:latest
          ports:
            - containerPort: 9000
          volumeMounts:
           - name: laravel-storage
             mountPath: /var/www/html/storage  