apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: laravel-data # Sets PV's name
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: local
  capacity:
    storage: 30Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/home/ubuntu/laravel" # Sets the volume's path

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc-storage
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

