apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  annotations:
    argocd-image-updater.argoproj.io/git-branch: staging
    argocd-image-updater.argoproj.io/image-list: hotel=tazamun/hotel:stag1.0
    argocd-image-updater.argoproj.io/hotel.update-strategy: newest-build
    argocd-image-updater.argoproj.io/hotel.pull-secret:  dockerhub-secret
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: Kustomization
spec:
  replicas: 2


