
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo17
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo17
      DB_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8069:8069"
    networks:
      - odoo-network

volumes:
  postgres_data:

networks:
  odoo-network:
