resources: 
 - ../../base

namespace: sqa

namePrefix:
  sqa-

nameSuffix:
  -v1

patchesStrategicMerge:
- replicas.yaml
  

configMapGenerator:
- name: postgres-config
  env: config.properties
  namespace: sqa
