resources: 
 - ../../base


namespace: prod

namePrefix:
  prod-

nameSuffix:
  -v1

patchesStrategicMerge:
- replicas.yaml
  
configMapGenerator:
- name: postgres-config
  env: config.properties
  namespace: prod
