resources: 
 - ../../base

namespace: default 


namePrefix:
  dev-

nameSuffix:
  -v1

patchesStrategicMerge:
- replicas.yaml


configMapGenerator:
- name: postgres-config
  env: config.properties
  namespace: dev

